### ISSUE TITLE
Get rid of multiple_sep

### ISSUE THREAD

**Issue by rcannood** [viash-hub/biobox#77]
I see `gffread`, `multiqc`, and `samtools_stats` are overriding the `multiple_sep`. I'm trying to get `multiple_sep` standardised to `;` so we can eventually deprecate the setting (it's annoying to have to look up what the multiple separator is).

Could these following components be fixed? You'll also need to adapt the scripts and tests accordingly.

- [ ] @emmarousseau: gffread
- [x] @dorien-er: multiqc
- [ ] @emmarousseau: samtools_stats

## MultiQC

From:

```yaml
      - name: "--include_modules"
        type: string
        multiple: true
        multiple_sep: ","
        example: fastqc,cutadapt
        description: Use only these module
```

To:

```yaml
      - name: "--include_modules"
        type: string
        multiple: true
        example: [fastqc, cutadapt]
        description: Use only these module
```

(there are 4 instances in total)

## Samtools

From:

```yaml
    - name: --coverage
      alternatives: -c
      type: integer
      description: |
        Coverage distribution min,max,step [1,1000,1].
      multiple: true
      multiple_sep: ','
```

To:

```yaml
    - name: --coverage
      alternatives: -c
      type: integer
      description: |
        Coverage distribution min,max,step. Default: [1, 1000, 1].
      multiple: true
      example: [1, 1000, 1]
```

## GFFread

From:

```yaml
      - name: --table
        type: string
        multiple: true
        multiple_sep: ","
        description: |
          Output a simple tab delimited format instead of GFF, with columns having the values 
          of GFF attributes given in <attrlist>; special pseudo-attributes (prefixed by @) are 
          recognized:
            @id, @geneid, @chr, @start, @end, @strand, @numexons, @exons, @cds, @covlen, @cdslen
          If any of --spliced_exons/--tr_cds/--spliced_cds FASTA output files are enabled, the 
          same fields (excluding @id) are appended to the definition line of corresponding FASTA
          records.
```

To

```yaml
      - name: --table
        type: string
        multiple: true
        description: |
          Output a simple tab delimited format instead of GFF, with columns having the values 
          of GFF attributes given in <attrlist>; special pseudo-attributes (prefixed by @) are 
          recognized:
            @id, @geneid, @chr, @start, @end, @strand, @numexons, @exons, @cds, @covlen, @cdslen
          If any of --spliced_exons/--tr_cds/--spliced_cds FASTA output files are enabled, the 
          same fields (excluding @id) are appended to the definition line of corresponding FASTA
          records.
```
