### ISSUE TITLE
Add authorship to components

### ISSUE THREAD

**Issue by rcannood** [viash-hub/biobox#80]
I think components should mention a list of authors / contributors. In OpenPipeline this is addressed by:

* Storing a list of authors in [src/authors](https://github.com/openpipelines-bio/openpipeline/tree/main/src/authors).
* Merging the individual yaml in the components, e.g.:
  ```yaml
  authors:
    - __merge__: /src/authors/dries_de_maeyer.yaml
      roles: [ maintainer, author ]
    - __merge__: /src/authors/dries_schaumont.yaml
      roles: [ author ]
  ```

We could do the same, namely:

* [ ] Create a bunch of `src/authors` yamls
* [ ] Refer to the author yamls in the components
* [ ] Update the contribution documentation to reflect these changes
